---
title: "Data Cleaning"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, warning=FALSE}
library(data.table)
library(RCurl)
library(XML)
library(rvest)
library(magrittr)
```

Loading data into R using data.table package

```{r loading file, warning=FALSE}
dat <- fread("iproperty.csv")
```

##Cleaning data

```{r cleaning, results= 'hide'}
#remove colon and trailing spaces
names(dat) <- trimws(sub(" :$", "", names(dat)))

# set factor for selected columns
factor.cols <- c("Property Type", "Bedrooms", "Bathrooms", "Tenure", "Estate", "Unit Type", "Carpark", "Air Cond", "District")
for (j in factor.cols) set(dat, j = j, value = as.factor(dat[[j]]))

#combine two name versions taken from different pages
combineTwoColumns <- function (dt, regex) {
  colnames <- dt[, names(.SD), .SDcols = names(dt) %like% regex]
  dt[is.na(get(colnames[1])) | get(colnames[1]) == "View to offer", colnames[1] := get(colnames[2])][, (colnames[2]) := NULL]
}

combineTwoColumns(dat, "^Asking.*(?i)psm")
combineTwoColumns(dat, "^Asking.*(?i)psf")

# set numeric for dollar values
dollar.cols <- dat[, names(.SD), .SDcols = names(dat) %like% "Asking|(?i)psf|(?i)psm" | names(dat) == "Age"]
for (j in dollar.cols) set(dat, j=j, value=(as.numeric(gsub("SGD| |,","",dat[[j]]))))

# convert rows in sq. m. to sq. ft
area.cols = c("Built up", "Land")
for (j in area.cols) dat[, paste0(j,"_sqft") := ifelse(get(j) %like% "sq. m", as.numeric(gsub(" sq. m", "", get(j))) * 10.7639, as.numeric(gsub(" sq. ft.", "", get(j))))]

# Calculate missing Asking Price (PSF)
# note given PSM actually means PSF, but below code uses Asking Price and area to calculate PSF
dat[is.na(`Asking (PSF)`), `Asking (PSF)` := `Asking Price` / `Built up_sqft`]
``` 

Converting Esate Data to district number 
```{r estate to district}
## Change Estate Location to District Number 
regexes <- {list(c("(Boat Quay|Chinatown|Havelock Road|Marina Square|Raffles Place|Suntec City)",1),
                c("(Anson Road|Chinatown|Neil Road|Raffles Place|Shenton Way|Tanjong Pagar)",2),
                c("(Alexandra Road|Tiong Bahru|Queenstown)",3),
                c("(Keppel|Mount Faber|Sentosa|Telok Blangah)",4),
                c("(Buona Vista|Dover|Pasir Panjang|West Coast)",5),
                c("(City Hall|High Street|North Bridge Road)",6),
                c("(Beach Road|Bencoolen Road|Bugis|Rochor)",7),
                c("(ittle India|Farrer Park|Serangoon Road)",8),
                c("(Cairnhill|Killiney|Leonie Hill|Orchard|Oxley)",9),
                c("(Balmoral|Bukit Timah|Grange Road|Holland|Orchard Boulevard|River Valley|Tanglin Road)",10),
                c("(Chancery|Dunearn Road|Newton)",11),
                c("(Balestier|Moulmein|Novena|Toa Payoh)",12),
                c("(Potong Pasir|Macpherson)",13),
                c("(Eunos|Geylang|Kembangan|Paya Lebar)",14),
                c("(Katong|Marine Parade|Siglap|Tanjong Rhu)",15),
                c("(Bayshore|Bedok|Chai Chee)",16),
                c("(Changi|Loyang|Pasir Ris)",17),
                c("(Simei|Tampines)",18),
                c("(Hougang|Punggol|Sengkang)",19),
                c("(Ang Mo Kio|Bishan|Braddell Road|Thomson)",20),
                c("(Clementi|Upper Bukit Timah|Hume Avenue)",21),
                c("(Boon Lay|Jurong|Tuas)",22),
                c("(Bukit Batok|Choa Chu Kang|Hillview Avenue|Upper Bukit Timah)",23),
                c("(Kranji|Lim Chu Kang|Sungei Gedong|Tengah)",24),
                c("(Admiralty|Woodlands)",25),
                c("(Tagore|Yio Chu Kang)",26),
                c("(Admiralty|Sembawang|Yishun)",27),
                c("(Seletar|Yio Chu Kang)",28))
}


                           for(i in seq_along(regexes)){
dat$District[grepl(x = dat$Estate, pattern = regexes[[i]][1])] <- regexes[[i]][2]
                           }
```
Getting District Data from the web and merging them 
```{r crawl district info}
url <- "https://keylocation.sg/singapore/districts-map"
urldata<-getURL(url)
data <-readHTMLTable(urldata)
Region <- read_html(url) %>% html_nodes('h3') %>% html_text()
data <- data[1:5]
for (i in 1:5){
  data[[i]]$Region <- Region[i]
}
district.data<- do.call(rbind,data)
dat <- merge(dat,district.data, by.x = "District", by.y= "District",all = TRUE)
```

```{r}
# Group less frequent property types into "Others"
dist <- as.data.table(table(dat$`Property Type`))
names(dist) <- c("Property Type", "P.Type.Freq")
dist[, property.type.new := ifelse(P.Type.Freq < 200, "Others", `Property Type`)]
dat <- merge(dat, dist, by = "Property Type", all=TRUE)
```

Write cleaned data into CSV
```{r writing to csv}
fwrite(dat, file="iproperty_cleaned.csv")
```




